### PR TITLE
Setup Sun*CI

### PR DESCRIPTION
**Pull request by thanhnn-3239**
## Related Tickets
- [Task#50938](https://edu-redmine.sun-asterisk.vn/issues/50938)

## WHAT (optional)
- Setup Sun*CI

## HOW
- Setup SUN*CI

## WHY (optional)
- Theo yêu cầu

### CODE REVIEW

**Comment by thanhnn-3239** [comment]
ready

**Comment by thanhnn-3239** [comment]
ready

**Comment by thanhnn-3239** [comment]
ready

**Review by huongnt-2545 — APPROVED** [review]
merged

**Pull request merged**
